NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

**What is an array**


An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [6]:
arr = np.array(my_list)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [9]:
arr.shape   # This is shape of an array it is 1-d array

(5,)

In [11]:
my_list1 = [1,2,3,4,5]
my_list2 = [2,3,4,5,6]
my_list3 = [3,4,5,6,7]

arr1 = np.array([my_list1, my_list2, my_list2]) # observe the squre braces here

In [12]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6]])

In [13]:
arr1.shape

(3, 5)

In [18]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 2, 3],
       [4, 5, 6]])

In [24]:
print(arr1)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [2 3 4 5 6]]


In [20]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

**indexing**

In [25]:
print(arr1[0])
print(arr1[2])

[1 2 3 4 5]
[2 3 4 5 6]


In [30]:
arr1[:,:]   # [rows, column]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6]])

In [33]:
arr1[1:,:]  # all from 1st row onwards

array([[2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6]])

In [45]:
print(arr1[0:1,0:1])    # arr1[0][0]
print('---')
print(arr1[0:2, 0:2])    #row 0,1 and column 0,1
print('---')
print(arr1[0:2,3:5])     # row 0,1 and column 3,4
print('---')
arr1[1:,2:4]

[[1]]
---
[[1 2]
 [2 3]]
---
[[4 5]
 [5 6]]
---


array([[4, 5],
       [4, 5]])

In [51]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(0,10,step=2)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [54]:
np.linspace(0,10,num=20)  

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

**copy function and broad casting**

In [55]:
# copy function and broad casting
arr = np.arange(1,10)

In [56]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr[3:]=100

In [70]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [71]:
arr1=arr
print(arr1)

[  1   2   3 100 100 100 100 100 100]


In [72]:
arr1[3:]=500
print(arr1)           # arr1 also got modified because array is a reference type.
print(arr)

[  1   2   3 500 500 500 500 500 500]
[  1   2   3 500 500 500 500 500 500]


In [76]:
arr1=arr.copy()      # to avoid the above issue of copying

In [77]:
print(arr)
arr1[3:]=700
print(arr)

[  1   2   3 500 500 500 500 500 500]
[  1   2   3 500 500 500 500 500 500]


In [78]:
print(arr1)

[  1   2   3 700 700 700 700 700 700]


In [80]:
val=2
print(arr1==val)
print(arr1>val)
print(arr1*val)
print(arr1%val)
print(arr1/val)


[False  True False False False False False False False]
[False False  True  True  True  True  True  True  True]
[   2    4    6 1400 1400 1400 1400 1400 1400]
[1 0 1 0 0 0 0 0 0]
[  0.5   1.    1.5 350.  350.  350.  350.  350.  350. ]


In [85]:
print(arr1>3)
print(arr1[arr1>3])

[False False False  True  True  True  True  True  True]
[array([False, False, False,  True,  True,  True,  True,  True,  True])]
[700 700 700 700 700 700]


In [87]:
np.ones(4)

array([1., 1., 1., 1.])

In [90]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [93]:
np.random.rand(3,3)

array([[0.73385525, 0.72139883, 0.69378628],
       [0.16282501, 0.07818637, 0.73412588],
       [0.20818509, 0.46096286, 0.25640529]])

In [92]:
np.random.randn(3,3)

array([[ 2.00625512,  1.76845989, -1.36564249],
       [ 1.07537371,  0.95195037, -0.42061991],
       [ 0.05493689,  0.75528272,  1.73395664]])